Close Sentry.io
pittcsc/Summer2023-Internships pull request #1088
Opened 2022-08-25 05:40 UTC by Urmi-Jana

Based on #1075

2022-08-25 14:16 UTC, parth-commits commented
if its closed, i think you should remove the link

2022-08-25 14:44 UTC, Zmwang622 requested changes

2022-08-25 14:44 UTC, Zmwang622 commented on README.md
> +| [Sentry.io](https://sentry.io/careers/internships/) | San Francisco, Toronto, Vienna | **🔒 Closed 🔒** Software Engineer, Intern (Summer 2023) |
please remove the link, thanks!

2022-08-25 14:58 UTC, Urmi-Jana commented
Removed the link. Thanks for pointing it out!

2022-08-26 02:17 UTC, Zmwang622 commented
Appreciate it!

2022-08-26 02:17 UTC, merged