Added more internships
pittcsc/Summer2023-Internships pull request #1227
Opened 2022-09-21 13:52 UTC by shailim

2022-09-21 18:35 UTC, Zmwang622 requested changes

2022-09-21 18:35 UTC, Zmwang622 commented on README.md
> +| CyberArk | Remote USA | [Software Engineer Intern](https://careers.cyberark.com/job/Identity-Software-Engineer-Intern/830434501/) |
please put the link on the leftside column!  (like what you did with TripActions)

2022-09-21 18:35 UTC, Zmwang622 commented on README.md
> +| Reliable Robotics | Mountain View, CA | Flight Software Engineer Intern: [Summer](https://jobs.lever.co/reliable/90367300-93c0-4b0f-8893-13ebd4af326d/apply?lever-source=LinkedIn), [Winter/Spring 20
let's keep this repo to Summer only internships!

2022-09-22 00:31 UTC, owini commented
@Zmwang622 will save for you to approve 👍

2022-09-22 23:33 UTC, Zmwang622 approved these changes

2022-09-22 23:34 UTC, merged