Add Climate, Anthology, Marvell
pittcsc/Summer2023-Internships pull request #1302
Opened 2022-10-03 23:18 UTC by 0AYU0

2022-10-03 23:29 UTC, ewang2002 requested changes
See suggestions. Looks good otherwise!

2022-10-03 23:29 UTC, ewang2002 commented on README.md
> +| [Anthology Inc](https://careers.anthology.com/jobs/10568474-software-engineering-intern?source=LinkedIn-JS) | Remote | Software Engineering Intern |
Anthology: make it clear that "This position is not available for candidates residing in the following states: CO, CA, MA." Add something like "(Not available for residents of CO, CA, MA)"

2022-10-03 23:29 UTC, ewang2002 commented on README.md
> +| [Climate](https://jobs.jobvite.com/careers/the-climate-corporation/job/otfWkfwI?__jvst=Job%20Board&__jvsd=LinkedIn) | San Francisco, California  Seattle, Washington  Chicago, Illinois  St. Louis, M
Separate the locations out, or just put `Multiple` instead

2022-10-04 14:23 UTC, owini approved these changes

2022-10-04 14:24 UTC, merged

2022-10-04 14:24 UTC, owini commented
Thanks, both!