Added snowflake, Roche and SUBCOM
pittcsc/Summer2023-Internships pull request #1463
Opened 2022-11-01 07:27 UTC by tchan102

2022-11-01 12:30 UTC, ewang2002 requested changes
See my one comment.

I'll let the others decide what should be done about SUBCOM.

2022-11-01 12:30 UTC, ewang2002 commented on README.md
> +| [SUBCOM](https://ekwo.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/2119) | Newington, NH | Software Developer Intern |
SUBCOM concerns me. Specifically, they are 
> Only considering candidates within 60 miles of Newington, NH

There is no mention of relocation anywhere, so I'm tempted to just remove SUBCOM altogether.

I'll let the others decide what to do with SUBCOM.

2022-11-01 12:31 UTC, ewang2002 commented on README.md
> +| [SUBCOM](https://ekwo.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/2119) | Newington, NH | Software Developer Intern |
Oops, I meant to select "Comment" not "Request Changes." Don't worry about making any changes for now.

2022-11-02 05:16 UTC, tchan102 commented
deleted the SUBCOM need another review to pass the merge

2022-11-02 12:00 UTC, ewang2002 approved these changes
Looks good, thank you!

2022-11-02 12:00 UTC, merged

2022-11-02 12:01 UTC, ewang2002 commented
> deleted the SUBCOM need another review to pass the merge

Feel free to request another review from me if I do review your PR and request changes.