Fix broken off-season link
pittcsc/Summer2023-Internships pull request #2986
Opened 2023-10-15 05:31 UTC by hainesdata

2023-10-15 05:33 UTC, hainesdata commented
#2985

2023-10-15 16:50 UTC, sharunkumar requested changes

2023-10-15 16:50 UTC, sharunkumar commented on README.md
> +> For off-season internships, please see the [Off-Season 2024 README](https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/README-Off-Season.md).
I think changing it to `(README-Off-Season.md)`  should work :thinking:

2023-10-15 16:57 UTC, sharunkumar commented on README.md
> +> For off-season internships, please see the [Off-Season 2024 README](https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/README-Off-Season.md).
Strange, this used to work: https://github.blog/2013-01-31-relative-links-in-markup-files/

Maybe something is broken on github's side

2023-10-16 14:00 UTC, Rbeautelus1 commented
STOP

On Sun, Oct 15, 2023 at 1:00 PM Sharun ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/SimplifyJobs/Summer2024-Internships/pull/2986#discussion_r1359912350>
> :
>
> > -> For off-season internships, please see the [Off-Season 2024 README](./README-Off-Season.md).
> +> For off-season internships, please see the [Off-Season 2024 README](https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/README-Off-Season.md).
>
> Strange, this used to work:
> https://github.blog/2013-01-31-relative-links-in-markup-files/
>
> Maybe something is broken on github's side
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SimplifyJobs/Summer2024-Internships/pull/2986#discussion_r1359912350>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYV73IAVD4N7SW7MXHZMTJLX7QJC5ANCNFSM6AAAAAA6AYIJ6A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: <SimplifyJobs/Summer2024-Internships/pull/2986/review/1678830239@
> github.com>
>

2023-10-19 05:58 UTC, closed without merging