Workflow and script to sort readme
pittcsc/Summer2023-Internships pull request #3427
Opened 2023-12-04 18:33 UTC by bearsyankees

2023-12-04 18:35 UTC, bearsyankees commented
fix for #3361

2023-12-05 15:43 UTC, bearsyankees commented
@yan-michael thoughts? :)

2023-12-13 07:08 UTC, rushilsrivastava requested changes
Hey! Thanks for the contribution! I think instead of making another action, it's best to expand upon the code @matttreed wrote and modify the `sortListings` function [here](https://github.com/SimplifyJobs/Summer2024-Internships/blob/dev/.github/scripts/util.py#L132-L159).

2023-12-13 21:04 UTC, bearsyankees commented
Good call. That line should do it :) @rushilsrivastava

2023-12-15 18:58 UTC, Kartikay77 approved these changes

2023-12-15 22:46 UTC, rushilsrivastava requested changes

2023-12-15 22:46 UTC, rushilsrivastava commented on .github/scripts/util.py
> +            datetime.fromtimestamp(x["date_posted"]),
This doesn't strip out hours, minutes, seconds, and microseconds from the timestamp, so it won't group postings from the same company on the same day together.
```suggestion
            datetime(
                datetime.fromtimestamp(x["date_posted"]).year,
                datetime.fromtimestamp(x["date_posted"]).month,
                datetime.fromtimestamp(x["date_posted"]).day
            ),
```

2023-12-15 22:47 UTC, merged